version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: pokemon-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com

  frontend:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: pokemon-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./app:/app
    depends_on:
      - backend

