# Generated by Django 5.2.5 on 2025-08-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('plataforma', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('sin iniciar', 'Sin Iniciar'), ('jugando', 'Jugando'), ('completado', 'Completado')], default='sin iniciar', max_length=20)),
            ],
        ),
    ]
