# Generated by Django 5.0.6 on 2025-08-12 04:27

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Juego', 'verbose_name_plural': 'Juegos'},
        ),
        migrations.AddField(
            model_name='game',
            name='calificacion',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Calificación (1-10)'),
        ),
        migrations.AddField(
            model_name='game',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='game',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AddField(
            model_name='game',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
        ),
        migrations.AddField(
            model_name='game',
            name='fecha_lanzamiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Lanzamiento'),
        ),
        migrations.AddField(
            model_name='game',
            name='genero',
            field=models.CharField(choices=[('rpg', 'RPG'), ('accion', 'Acción'), ('aventura', 'Aventura'), ('estrategia', 'Estrategia'), ('deportes', 'Deportes'), ('otros', 'Otros')], default='rpg', max_length=20, verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='game',
            name='horas_jugadas',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Horas Jugadas'),
        ),
        migrations.AddField(
            model_name='game',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='games/', verbose_name='Imagen del Juego'),
        ),
        migrations.AlterField(
            model_name='game',
            name='estado',
            field=models.CharField(choices=[('sin iniciar', 'Sin Iniciar'), ('jugando', 'Jugando'), ('completado', 'Completado'), ('abandonado', 'Abandonado')], default='sin iniciar', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='game',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre del Juego'),
        ),
        migrations.AlterField(
            model_name='game',
            name='plataforma',
            field=models.CharField(max_length=50, verbose_name='Plataforma'),
        ),
    ]
